"""empty message

Revision ID: eefd6befeb36
Revises: fbbb2aea1356
Create Date: 2026-04-20 01:22:53.541728

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = "eefd6befeb36"
down_revision: Union[str, Sequence[str], None] = "fbbb2aea1356"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "tasks_changelogs",
        "changed_by_id",
        existing_type=mysql.INTEGER(),
        nullable=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "tasks_changelogs",
        "changed_by_id",
        existing_type=mysql.INTEGER(),
        nullable=False,
    )
    # ### end Alembic commands ###
