"""empty message

Revision ID: fbbb2aea1356
Revises: 12b87057be4b
Create Date: 2026-04-19 19:31:34.216484

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = "fbbb2aea1356"
down_revision: Union[str, Sequence[str], None] = "12b87057be4b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "tasks_changelogs",
        "task_id",
        existing_type=mysql.INTEGER(),
        nullable=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "tasks_changelogs",
        "task_id",
        existing_type=mysql.INTEGER(),
        nullable=False,
    )
    # ### end Alembic commands ###
