"""empty message

Revision ID: 6ef009ee6b1c
Revises: 31847297e1c9
Create Date: 2026-04-18 21:24:18.968078

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = "6ef009ee6b1c"
down_revision: Union[str, Sequence[str], None] = "31847297e1c9"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "tasks", "created_by_id", existing_type=mysql.INTEGER(), nullable=True
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "tasks", "created_by_id", existing_type=mysql.INTEGER(), nullable=False
    )
    # ### end Alembic commands ###
