"""empty message

Revision ID: 31847297e1c9
Revises: fad48ad002e5
Create Date: 2026-04-18 20:27:09.152101

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "31847297e1c9"
down_revision: Union[str, Sequence[str], None] = "fad48ad002e5"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("tasks", sa.Column("description", sa.Text(), nullable=True))
    op.create_index(
        op.f("ix_tasks_priority"), "tasks", ["priority"], unique=False
    )
    op.create_index(op.f("ix_tasks_status"), "tasks", ["status"], unique=False)
    op.add_column(
        "users",
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "created_at")
    op.drop_index(op.f("ix_tasks_status"), table_name="tasks")
    op.drop_index(op.f("ix_tasks_priority"), table_name="tasks")
    op.drop_column("tasks", "description")
    # ### end Alembic commands ###
